haproxy:
  image: eeacms/haproxy
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes
  links:
  - plone
  environment:
  - BACKENDS=plone
  - BACKENDS_PORT=8080
  - DNS_ENABLED=true
  - TZ=Europe/Copenhagen

memcached:
  image: eeacms/memcached
  environment:
  - MEMCACHED_MEMORY=2048
  - TZ=Europe/Copenhagen
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes

postfix:
  image: eeacms/postfix:eionet
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes
  environment:
  - MTP_HOST=eni-seis.eionet.europa.eu
  - MTP_USER=${POSTFIX_USER}
  - MTP_PASS=${POSTFIX_PASS}
  - TZ=Europe/Copenhagen

plone:
  image: eeacms/plone-eni-seis:5.5.8
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes
    io.rancher.container.pull_image: always
  links:
  - zeoserver
  - memcached
  - postfix
  environment:
  - ZOPE_MODE=zeo_client
  - TZ=Europe/Copenhagen

async:
  image: eeacms/plone-eni-seis:5.5.8
  labels:
    io.rancher.scheduler.affinity:host_label: eni-seis=yes
    io.rancher.container.pull_image: always
  links:
  - zeoserver
  - memcached
  - postfix
  environment:
  - ZOPE_MODE=zeo_async
  - TZ=Europe/Copenhagen

zeoserver:
  image: eeacms/plone-eni-seis:5.5.8
  labels:
    io.rancher.sidekicks: data
    io.rancher.scheduler.affinity:host_label: eni-seis-data=yes
    io.rancher.container.pull_image: always
  volumes_from:
  - data
  environment:
  - ZOPE_MODE=zeoserver
  - TZ=Europe/Copenhagen

data:
  image: busybox
  labels:
    io.rancher.container.start_once: 'true'
  tty: true
  stdin_open: true
  volumes:
  - eni-seis-filestorage:/data/filestorage
  - eni-seis-blobstorage:/data/blobstorage
  command: ["chown", "-R", "500:500", "/data"]
